#!/usr/bin/env python3
"""Vendor the Google Fonts the dashboard uses into web/public/fonts.

The control center pulls Bodoni Moda, Inter, JetBrains Mono and Material
Symbols Outlined from fonts.googleapis.com at runtime. That's a hard external
dependency at page load: in an air-gapped or egress-restricted deployment the
icon font silently fails and every `<span class="mi">search</span>` renders as
the literal word "search". Vendoring the woff2 files removes the dependency.

Only the latin + latin-ext subsets are kept — the dashboard has no CJK/Cyrillic
copy, and pulling every subset would 5x the payload for nothing.

Run from the repo root:  python tools/vendor_fonts.py
"""
from __future__ import annotations

import os
import pathlib
import re
import sys
import urllib.request

# This lives in tools/, so the repo root is one level up.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from console import force_utf8  # noqa: E402

force_utf8()

UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
OUT_DIR = pathlib.Path("web/public/fonts")

SOURCES = {
    "text": "https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400..900;1,6..96,400..900&family=Inter:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap",
    "icons": "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL@20..48,100..700,0..1&display=swap",
}

# Google prefixes each @font-face with a `/* <subset> */` comment. Material
# Symbols labels its single block `/* fallback */` rather than by script, so
# that label has to be kept too or the icon font silently never downloads.
KEEP_SUBSETS = {"latin", "latin-ext", "fallback", None}

FACE_RE = re.compile(r"(?:/\*\s*(?P<subset>[\w-]+)\s*\*/\s*)?(?P<face>@font-face\s*\{[^}]*\})", re.S)
URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    combined: list[str] = [
        "/* Vendored Google Fonts — generated by tools/vendor_fonts.py.",
        "   Do not hand-edit; re-run the script to refresh. */",
        "",
    ]
    downloaded = 0

    for name, css_url in SOURCES.items():
        print(f"Fetching {name} CSS…")
        css = fetch(css_url).decode()

        for m in FACE_RE.finditer(css):
            subset = m.group("subset")
            if subset not in KEEP_SUBSETS:
                continue
            face = m.group("face")

            def replace(um: re.Match) -> str:
                nonlocal downloaded
                remote = um.group(1)
                fname = remote.rstrip("/").split("/")[-1]
                if not fname.endswith(".woff2"):
                    fname += ".woff2"
                dest = OUT_DIR / fname
                if not dest.exists():
                    print(f"  ↓ {fname}")
                    dest.write_bytes(fetch(remote))
                    downloaded += 1
                return f"url(/static/fonts/{fname})"

            combined.append(URL_RE.sub(replace, face))
            combined.append("")

    css_path = OUT_DIR / "fonts.css"
    css_path.write_text("\n".join(combined))
    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2"))
    print(f"\nWrote {css_path} ({downloaded} new woff2 files, {total/1024:.0f} KB total on disk).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
